apiVersion: v1
kind: Pod
metadata:
  name: pod-name
  namespace: git-created
  labels:
    image-policy.k8s.io/break-glass: "true"
spec:
  containers:
  - name: container-name
    image: nginx:latest
